config/routes.rb
Rails.application.routes.draw do
  root 'listings#index'

  devise_for :realtors

  resources :realtors do
    resources :listings
    resources :inqueries 
  end

  resources :listings do
    resources :inqueries
  end

  

  

end

app/models/inquery.rb
class Inquery < ActiveRecord::Base
  belongs_to :listing
  belongs_to :realtor
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :inqueries
  belongs_to :realtor

  has_attached_file :avatar, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/realtor.rb
class Realtor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
  has_many :inqueries

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :company_name, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :company_name, :avatar, :current_password) }
  end

  def after_sign_in_path_for(resource)
    listings_path
  end
end

app/controllers/inqueries_controller.rb
class InqueriesController < ApplicationController
 before_action :params_id, only: [:show, :edit, :destroy]
 def show
 end

 def index
   #@realtor = current_realtor
   #@inqueries = current_realtor.inqueries
   @inqueries = Inquery.where(:realtor_id => params[:realtor_id])
   #@listings = Realtor.find(params[:realtor_id]).listings.map(&:id)
   #@inqueries = Inquery.where(listing_id: @listings)
 end

 def edit
 end

 def new
   @inquery = Inquery.new
   @listing = Listing.find(params[:listing_id])
 end

 def create
   @inquery = Inquery.new
   if @inquery.save(inquery_params)
     flash[:notice] = 'Inquery Successfully Created'
     redirect_to listings_path
   else
     render :new
   end
 end

 def destroy
   if @inquery.destroy
     redirect_to listings_path
   else
     redirect_to inquery_path(@inquery) 
   end
 end

 private
 
 def params_id
   @inquery = Inquery.find(params[:id])
 end

 def inquery_params
   params.require(:inquery).permit(:first_name, :last_name, :phone_number, :email, :realtor_id)
 end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only: [:show, :edit, :destroy, :update]

  def index
    @listings = Listing.all
    @listing = Listing.new if realtor_signed_in?
    @realtor = current_realtor
  end

  def show
    @inqueries = @listing.inqueries
    @realtor = Realtor.find(current_realtor) if current_realtor
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      @listing.update(realtor_id: params[:realtor_id])
      redirect_to listings_path
    else
      render :new  
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to listings_path(@listing)
    else
      render :edit
    end
  end

  def destroy
    if @listing.destroy
      redirect_to listings_path
    else
      redirect_to listing_path(@listings) 
    end
  end


  private
    def listing_params
      params.require(:listing).permit(:address, :description, :zip, :square_footage, :realtor_id, :avatar)
    end
   
    def find_listing
      @listing = Listing.find(params[:id])
    end
end

app/controllers/realtors_controller.rb
class RealtorsController < ApplicationController
  before_action :params_id, only: [:show, :update, :edit, :destroy]
  def index
    @realtor = Realtor.find(params[:realtor_id])
    @listings = Listing.where(realtor_id: @realtor)
  end

  def show
  end

  def new
    @realtor = Realtor.new
  end

  def create
    @realtor = Realtor.new(realtor_params)
    if @realtor.save
      redirect_to realtors_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @realtor.update(realtor_params)
      flash[:notice] = "Profile Successfully Changed"
      redirect_to listings_path
    else
      render :edit
    end
  end

  def destroy
    if @realtor.destroy
      redirect_to realtors_path
    else
      redirect_to realtor_path(@realtor)
    end
  end

  private
    def realtor_params
      params.require(:realtor).permit(:first_name, :last_name, :company_name, :phone_number, :avatar, :realtor_id)
    end

    def params_id
      @realtor = Realtor.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inqueries_helper.rb
module InqueriesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/realtors_helper.rb
module RealtorsHelper
end

app/views/inqueries/create.html.erb
<h1>Inqueries#create</h1>
<p>Find me in app/views/inqueries/create.html.erb</p>

app/views/inqueries/index.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <h2>Inqueries</h2>
 

    <ul class="collection">
    <% @inqueries.each do |inquery| %>
       <%= inquery.listing.address %>
        <li class="collection-item">
        <div>
        First Name: <%= inquery.first_name %>
        Last Name: <%= inquery.last_name %>
        Phone Number: <%= inquery.phone_number %>
        E-Mail: <%= inquery.email %>
        <%= link_to 'Delete Inquery', realtor_inquery_path(current_realtor, inquery), method: :delete, class: "secondary-content material-icons" %></div></li>
    <% end %> 
    </ul>
  </div>
</div>

app/views/inqueries/new.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <br />
    <%= form_for [@listing, @inquery] do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
        <br />
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
        <br />
        <%= f.label :phone_number %>
        <%= f.telephone_field :phone_number %>
        <br />
        <%= f.label :email %>
        <%= f.email_field :email %>
        <br />
        <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/inqueries/show.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <h3>Inquery for #{@listing.inquery.address}</h3>
    <%= inquery.first_name %>
    <%= inquery.last_name %>
    <%= inquery.phone_number %>
    <a href="mailto:<%= inquery.email %>"><%= inquery.email %></a>
        <% if realtor_signed_in? %>
          <h2><%= %></h2>
          <%= button_to 'Delete Inquery', realtor_inquery_path(@realtor), method: :delete %>
        <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<br />
<nav>
    <div class="nav-wrapper">
      <a href="/" class="waves-effect waves-light brand-logo z-depth-3 cyan lighten-1 " style="font-size: 70px;">Land List</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if realtor_signed_in? %>
          <li><%= link_to 'View Listings' , realtor_listings_path(current_realtor) %></li>
          <li><%= link_to 'View Inqueries', realtor_inqueries_path(current_realtor) %></li>
          <li><%= link_to 'Edit Profile', edit_realtor_registration_path %></li>
          <li><%= link_to 'Signout', destroy_realtor_session_path, method: :delete %></li>
         
        <% else %>
          <li><a href="/realtors/sign_in">Realtor Sign In</a></li>
          <li><a href="/realtors/sign_up">Realtor Signup</a></li>
          
        <% end %>
      </ul>
    </div>
  </nav>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LandList</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<span class="notice"><%= notice %></span>
<span class="alert"><%= alert %></span>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/listings/_form_for_realtor.html.erb
<% if realtor_signed_in? %>
  <%= form_for [@realtor, @listing] do |f|%>
    <%= f.file_field :avatar %>
    <br />
    <%= f.label :address %>
    <%= f.text_field :address %>
    <br />
    <%= f.label :zip %>
    <%= f.text_field :zip %>
    <br />
    <%= f.label :square_footage %>
    <%= f.number_field :square_footage %>
    <br />
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br />
    <%= f.submit 'Submit', class: 'btn', onclick: "Materialize.showStaggeredList('#staggered-test')" %>
  <% end %>
<% end %>

app/views/listings/edit.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <h2>Edit Listing</h2>
    <%= render(partial:'form_for_realtor') %>
  </div>
</div>

app/views/listings/index.html.erb
<div class="row">
  <div class="col s10 offset-s1">
  <br />
    <h2>Current Listings</h2>
    <br />
      <% if @listings.any? %>

    
    <div class="row">
        
          <% @listings.each do |listing| %>
        
               <div class="col s12 m4" style="min-height: 400px;">
                  <div class="card" >
                    <div class="card-image" >
                      <%= image_tag listing.avatar.url(:medium), class: "activator" %>
                      <span class="card-title"><%= listing.address %></span>
                    </div>
                    <div class="card-content">
                      <span class="activator">More Info</span>
                      <%= link_to "View Listing", listing_path(listing) %>
                    </div>
                    <div class="card-reveal">
                      <p><%= listing.description %></p>
                      <p>Square Footage: <%= listing.square_footage %></p>
                      <span class="card-title cyan-text">Hide Description</span>
                    </div>
                  </div>
                </div>
          <% end %>
        <% else %>
          <h3>No listings to show</h3>
      <% end %>
     <br />
  </div>
      <hr />
      <br />
    <%= render(partial:'form_for_realtor') %>
 </div>
</div>

app/views/listings/new.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <h2>Add New Listing</h2>
    <%= render(partial:'form_for_realtor') %>
  </div>
</div>

app/views/listings/show.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <br />
    <br />
    

    <%= image_tag @listing.avatar.url(:medium) %>

    <br />
    <h2><%= @listing.address %></h2>
    <br />
    <p>Listing Description: <%= @listing.description %></p>

    <p>Address: <%= @listing.address %></p>

    <p>Zip code: <%= @listing.zip %></p>

    <p>Square Footage: <%= @listing.square_footage %></p>
    
    <% if realtor_signed_in? %>
      <%= link_to 'Edit Listing', edit_realtor_listing_path(@realtor, @listing), class: "btn", onclick: "Materialize.showStaggeredList('#staggered-test')" %>
      <%= link_to 'Delete Listing', realtor_listing_path(@realtor, @listing), method: :delete, class: "btn", onclick: "Materialize.showStaggeredList('#staggered-test')" %>
      <% else %>
        <%= link_to 'Request Information', new_listing_inquery_path(@listing), class: "btn", onclick: "Materialize.showStaggeredList('#staggered-test')" %>
    <% end %>
  </div>
</div>

app/views/realtors/index.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <h2> 
      Welcome,
      <% if realtor_signed_in? %>
        <%= current_realtor.first_name %>
      <% end %>  
    </h2>
    <h2>Index Listings</h2>

    <br />
    <% if @listings.any? %>
      <ul>
        <% @listings.each do |listing| %>
          <li>
            <%= link_to "#{listing.first_name}", listing_path(listing) %>
            <%= button_to 'Edit Listing', edit_listing_path(listing), method: :get %>
            <%= button_to "Delete Listing", listing_path(listing), method: :delete, data: {confirm: 'Really delete this Listing?'} %>
          </li>
        <% end %>
      </ul>
      <% else %>
        <h2>No Listings</h2>
    <% end %>

  </div>
</div>

app/views/realtors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/realtors/show.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <h2>Realtors Profile</h2>
    <%= image_tag @realtor.avatar.url(:thumb) %>
    <h2> 
      Profile for,
      <%= current_realtor.first_name %>
    </h2>


    <%= link_to 'Edit Profile', edit_realtor_path(@realtor) %>
    <%= link_to 'Logout', destroy_realtor_session_path, method: :delete %>
  </div>
</div>